version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ../project:/var/www/laravel
      - ./nginx/:/etc/nginx/conf.d
    working_dir: /var/www/laravel
    links:
      - app

  app:
    container_name: app
    build: .
    volumes:
      - ../project:/var/www/laravel
    links:
      - postgres
    ports:
      - "9000:9000"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=toyStore_db
    ports:
      - 5432:5432

